name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      node:
        required: true
        type: string

jobs:
  call-workflow-passing-data:
    uses: dcharan/protractor/.github/workflows/ressuable_workflow.yml@master
    with:
      node: ${{ inputs.node }}
