name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: dcharan/protractor/.github/workflows/resuable_action/ressuable_workflow.yml@master
    with:
      node: 14