name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    uses: dcharan/protractor/.github/workflows/ressuable_workflow.yml@master
    with:
      node: 14