name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      node:
        required: true
        type: string
        default: "12"
      environment:
        required: true
        type: boolean
        default: false
        description: where its cert manager prod env or nonprod env
jobs:
  call-workflow-passing-data:
    uses: dcharan/protractor/.github/workflows/ressuable_workflow.yml@master
    with:
      node: ${{ inputs.node }}
      enviro: ${{ inputs.environment }}
