# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
        - name: A job to say hello
          uses: dcharan/protractor/resuable_action@master
          with: 
            hello_world_var: "charan from caller"

  # call_resuable:
