# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  # hello_world_job:
  #   runs-on: ubuntu-latest
  #   name: A job to say hello
  #   steps:
  #     - uses: actions/checkout@v4

  #     - run: cat random.txt 
  #       shell: bash

  #     - name: run oneline script
  #       run: echo "hello, world"

  call_resuable:
    uses: dcharan/protractor/.github/workflows/resuable.yml@master
    with: 
      image_name: "afdfd"
      tag: "sometag"
