name: Conditional Runner Workflow

on: 
  workflow_dispatch:
    inputs:
      runner:
        description: 'Define env name'     
        required: true
        default: 'default'

jobs:
  determine-environment:
    runs-on: ubuntu-latest 
      TEST_ENV: "test"
    steps:
      - name: Set runner type
        id: set-runner-type
        run: |
          if [[ "${{ github.event.inputs.runner }}" == "prod" || "${{ github.event.inputs.runner }}" == "prod-internal" || "${{ github.event.inputs.runner }}" == "prod-customer" ]]; then
            echo "::set-output name=runner-type::ubuntu-24.04"
          else
            echo "::set-output name=runner-type::ubuntu-latest"
          fi
    outputs:
      runner-type: ${{ steps.set-runner-type.outputs.runner-type }}  
      NEW_ENV: "new output value"


  hello_world_job:
    needs: determine-environment
    runs-on: ${{ needs.determine-environment.outputs.runner-type }}
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Say hello
        run: echo "Hello from ${{ needs.determine-environment.outputs.runner-type }} ${{ needs.determine-environment.outputs.NEW_ENV }}  environment!"
