name: Create AWS Secret

on:
  workflow_dispatch:
    inputs:
      secret-value:
        description: 'The value of the secret'
        required: true
        type: string

jobs:
  create-secret:
    runs-on: ubuntu-latest
    env:
      SECRET_VALUE: ${{ github.event.inputs.secret-value }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Masking Input Values
        run: |
          SECRET_VALUE=$(jq -r 'inputs["secret-value"] | @text' $GITHUB_EVENT_PATH)
          echo "::add-mask::$SECRET_VALUE"
          echo SECRET_VALUE=$SECRET_VALUE >> $GITHUB_ENV

      - name: print
        run: env
