name: Create AWS Secret

on:
  workflow_dispatch:
    inputs:
      secret-value:
        description: 'The value of the secret'
        required: true
        type: string

jobs:
  create-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set secret values
        run: |
          echo "::add-mask::${{ github.event.inputs.secret-value }}"
          echo "SECRET_VALUE=${{ github.event.inputs.secret-value }}" >> $GITHUB_ENV

      - name: print
        run: env
