name: Create AWS Secret

on:
  workflow_dispatch:
    inputs:
      secret-value:
        description: 'The value of the secret'
        required: true
        type: string

jobs:
  create-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Mask secret value
        run: echo "::add-mask::${{ github.event.inputs.secret-value }}"

      - name: Create AWS Secret
        run: echo ${{ github.event.inputs.secret-value }}
